list P=16F887 
#INCLUDE "P16F887.INC"
    __CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON
    __CONFIG _CONFIG2, _LVP_OFF & _BOR_OFF
 
 ORG 0X00
 GOTO INICIO
 ORG 0X05
 
 INICIO
 
BSF	STATUS,RP0
BSF	STATUS,RP1  ;banco 3
CLRF	ANSEL	 ;todos los puertos son dijitales
CLRF	ANSELH	 ;todos los puertos son dijitales
BCF	STATUS, RP1  ;banco 1
CLRF	TRISB	  ;PONGO ESTOS PUERTOS COMO SALIDA


    END
    
    
	 